/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;

/**
 *
 * @author Heber
 */
public class VistaCM extends javax.swing.JFrame {
    CuadradoMagico cm = new CuadradoMagico(3);
    /**
     * Creates new form VistaCM
     */
    public VistaCM() {
        initComponents();
         comprobar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        po2 = new javax.swing.JTextField();
        po7 = new javax.swing.JTextField();
        po8 = new javax.swing.JTextField();
        po9 = new javax.swing.JTextField();
        tituloCM = new javax.swing.JLabel();
        po00 = new javax.swing.JTextField();
        mensajes = new javax.swing.JLabel();
        po02 = new javax.swing.JTextField();
        po01 = new javax.swing.JTextField();
        po12 = new javax.swing.JTextField();
        po11 = new javax.swing.JTextField();
        po10 = new javax.swing.JTextField();
        po22 = new javax.swing.JTextField();
        po21 = new javax.swing.JTextField();
        po20 = new javax.swing.JTextField();
        comprobar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();

        po2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po2KeyReleased(evt);
            }
        });

        po7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po7KeyReleased(evt);
            }
        });

        po8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po8KeyReleased(evt);
            }
        });

        po9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po9KeyReleased(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloCM.setFont(new java.awt.Font("Pacifico", 0, 33)); // NOI18N
        tituloCM.setForeground(new java.awt.Color(0, 102, 102));
        tituloCM.setText("Cuadrado Magico");

        po00.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po00KeyReleased(evt);
            }
        });

        mensajes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mensajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajes.setText("Ingrese Datos");

        po02.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po02KeyReleased(evt);
            }
        });

        po01.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po01KeyReleased(evt);
            }
        });

        po12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po12KeyReleased(evt);
            }
        });

        po11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po11KeyReleased(evt);
            }
        });

        po10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po10KeyReleased(evt);
            }
        });

        po22.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po22KeyReleased(evt);
            }
        });

        po21.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po21KeyReleased(evt);
            }
        });

        po20.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        po20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        po20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                po20KeyReleased(evt);
            }
        });

        comprobar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        comprobar.setForeground(new java.awt.Color(51, 51, 51));
        comprobar.setText("Comprobar");
        comprobar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarActionPerformed(evt);
            }
        });

        limpiar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        limpiar.setForeground(new java.awt.Color(51, 51, 51));
        limpiar.setText("Limpiar");
        limpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comprobar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(po00, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(po01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(po02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(po10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(po11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(po12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(po20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(po21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(po22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCM))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensajes)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(po00, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(po02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(po01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(po10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(po12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(po11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(po20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(po22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(po21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprobar)
                    .addComponent(limpiar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Los siguientes son eventos KeyReleased correspondientes a cada textfield integrado
    en el frame donde cada uno realiza el mismo proceso comentado en el siguiente caso*/
    private void po00KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po00KeyReleased
        /* Enviamos el dato ingresado en el textfield junto con la posicion
        en que se va a guardar en la matriz "casillas" de la clase CuadradoMagico.
        A su vez imprimimos el String que el metodo guardarDato nos retorna en el mismo textfield.
        */
        po00.setText(cm.guardarDato(po00.getText(),0,0));
        // Comprobamos que la matriz se encuentra llena con datos validos
        if (cm.comprobarExistenciaDatos()){
        //Si es así, habilitamos el boton para comprobar el cuadrado magico...
            comprobar.setEnabled(true);
        } else {
         // De lo contrario el boton de bloquea    
              this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }      
    }//GEN-LAST:event_po00KeyReleased
        
    private void po02KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po02KeyReleased
        po02.setText(cm.guardarDato(po02.getText(),0,2));
        if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        }  else {
            this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po02KeyReleased

    private void po2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_po2KeyReleased

    private void po01KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po01KeyReleased
        po01.setText(cm.guardarDato(po01.getText(),0,1));
        if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        } else {
            this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po01KeyReleased

    private void po12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po12KeyReleased
        po12.setText(cm.guardarDato(po12.getText(),1,2));
        if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        }  else {
            this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po12KeyReleased

    private void po11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po11KeyReleased
         po11.setText(cm.guardarDato(po11.getText(),1,1));
         if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        }  else {
             this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po11KeyReleased

    private void po10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po10KeyReleased
        po10.setText(cm.guardarDato(po10.getText(),1,0));
        if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        }  else {
            this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po10KeyReleased

    private void po7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_po7KeyReleased

    private void po8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po8KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_po8KeyReleased

    private void po9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po9KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_po9KeyReleased

    private void po22KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po22KeyReleased
        po22.setText(cm.guardarDato(po22.getText(),2,2));
        if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        }  else {
            this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po22KeyReleased

    private void po21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po21KeyReleased
         po21.setText(cm.guardarDato(po21.getText(),2,1));
         if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        }  else {
             this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po21KeyReleased

    private void po20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_po20KeyReleased
       po20.setText(cm.guardarDato(po20.getText(),2,0));
       if (cm.comprobarExistenciaDatos()){
            comprobar.setEnabled(true);
        }  else {
           this.mensajes.setText("Ingrese datos");
             comprobar.setEnabled(false);
        }     
    }//GEN-LAST:event_po20KeyReleased

/* Imprime un texto en el label "mensajes" dependiendo si los datos ingresados
    corresponden a un cuadrado magico o no */
    private void comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarActionPerformed
       if (cm.comprobarCM()){
           this.mensajes.setText("Es un cuadrado magico!!");
       } else {
            this.mensajes.setText("Esto no es un cuadrado magico!!");
       }
    }//GEN-LAST:event_comprobarActionPerformed

/* El siguiente metodo ejecuta el metodo "limpiarcasillas" para limpiar la matriz
    casillas de la clase CuadradoMagico y a la vez deja en blanco cada textfield
    encontrado en el frame*/
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        System.out.println("Se limpia todo");
        cm.limpiarCasillas();
        cm.imprimeMatriz();
        po00.setText("");
        po01.setText("");
        po02.setText("");
        po10.setText("");
        po11.setText("");
        po12.setText("");
        po20.setText("");
        po21.setText("");
        po22.setText(""); 
        this.mensajes.setText("Ingrese datos");
    }//GEN-LAST:event_limpiarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprobar;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel mensajes;
    private javax.swing.JTextField po00;
    private javax.swing.JTextField po01;
    private javax.swing.JTextField po02;
    private javax.swing.JTextField po10;
    private javax.swing.JTextField po11;
    private javax.swing.JTextField po12;
    private javax.swing.JTextField po2;
    private javax.swing.JTextField po20;
    private javax.swing.JTextField po21;
    private javax.swing.JTextField po22;
    private javax.swing.JTextField po7;
    private javax.swing.JTextField po8;
    private javax.swing.JTextField po9;
    private javax.swing.JLabel tituloCM;
    // End of variables declaration//GEN-END:variables
}
